[main]
# this should be the discord token of the bot
token = "1234"


[secret_lab]
# change me to the id of the sl audits channel
audit = 5678

[discord]
# change me to the id of the discord audits channel
audit = 1234
# change me to the id of the stats channel
stats = 5678